---
- name: Add master/bastion to created_vms group
  add_host:
    name: "{{ item.ip }}"
    groups: created_vms
    instance_name: "{{ item.name }}"
  with_items:
    - { name: 'master', ip: '{{master_public_ip}}' }
    - { name: 'bastion', ip: '{{bastion_public_ip}}' }

- name: Add infra to created_vms group
  add_host:
    name: "{{ infra_public_ip }}"
    groups: created_vms
    instance_name: "infra"
  when: standalone_infra_node

- name: Add nodes to created_vms group
  add_host:
    name: "{{ item.public_ip }}"
    groups: created_vms
    instance_name: "node{{ item.index }}"
  with_items: "{{ nodes }}"

- name: Add master to created_nodes group
  add_host:
    name: "{{ item.ip }}"
    groups: created_nodes
    instance_name: "{{ item.name }}"
  with_items:
    - { name: 'master', ip: '{{master_public_ip}}' }

- name: Add infra to created_nodes group
  add_host:
    name: "{{ infra_public_ip }}"
    groups: created_nodes
    instance_name: "infra"
  when: standalone_infra_node

- name: Add nodes to created_nodes group
  add_host:
    name: "{{ item.public_ip }}"
    groups: created_nodes
    instance_name: "node{{ item.index }}"
  with_items: "{{ nodes }}"

- name: Master host
  add_host:
    name: "{{ master_public_ip}}"
    groups: master
    instance_name: master

- name: Infra host
  add_host:
    name: "{{ infra_public_ip}}"
    groups: infra
    instance_name: infra
  when: standalone_infra_node

- name: Set temporary infra_private_dns_name variable
  set_fact:
    infra_private_dns_name: "none"
  when: not standalone_infra_node

- name: Bastion host
  add_host:
    name: "{{ bastion_public_ip}}"
    groups: bastion
    instance_name: bastion
    availability_zone: "{{availability_zone}}"
    master_private_dns_name: "{{master_private_dns_name}}"
    infra_private_dns_name: "{{infra_private_dns_name}}"
    public_master_dns: "{{public_master_dns}}"
    nodes: "{{ nodes }}"
    bastion_public_ip: "{{bastion_public_ip}}"

- name: Gluster hosts
  add_host:
    name: "{{ item.public_ip }}"
    groups: gluster
    instance_name: "{{ item.index}}"
  with_items: "{{nodes[0:3]}}"
  when: install_gluster

